# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "uas" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/43755840-feb5-4c66-b0b3-0b9e31c5396d";
      fsType = "ext4";
    };

  # fileSystems."/home/jay" =
  #   { device = "/dev/disk/by-uuid/602e0292-cb3e-41a0-9844-3233b8d09ca7";
  #     fsType = "ext4";
  #   };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/20C2-4759";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # fileSystems."/var/lib/docker/overlay2/aef2d8360434e11f90737b0fc455a76f9c2b59d3b96446d06dbbd83659092235/merged" =
  #   { device = "overlay";
  #     fsType = "overlay";
  #   };

  fileSystems."/home/jay" =
    { device = "/dev/disk/by-uuid/fe351c4f-b67b-451a-8989-1ec4f7e59f54";
      fsType = "ext4";
      options = [ "noatime" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
